### PR TITLE
fix(deps): include dev deps 

### PR DESCRIPTION
**Pull request by scamden**
(especially because these often are there because of peer deps)

another quick bug fix. thanks again for this script!

### CODE REVIEW

**Comment by scamden** [comment]
oh just saw #7, any reason you haven't merged it yet? @Bessonov

**Comment by Bessonov** [comment]
@scamden the only reason is, that I was not aware that someone use it and because of failing build

**Comment by scamden** [comment]
i'm using it and it's great! thanks for mentioning it on that typescript issue! i think the build failure is just a mismatched node version on your build server. i've already published these changes under a fork for my company to use, but I thought I would contribute them back to the tool since it's really useful! i was going to make one more bug fix to not introduce a reference if the workspace package has no tsconfig.json (non typescript packages exist haha), let me know if you'd like me to contribute here or i can just live on my fork.

**Comment by Bessonov** [comment]
I'll try to fix the build and release a new version :+1:

**Comment by scamden** [comment]
awesome. i'll submit a pr for the other thing soon probably

**Comment by Bessonov** [comment]
Do you mean this one? https://github.com/Bessonov/set-project-references/pull/5 I didn't merge it yet, because it was not tested enough.

**Comment by Bessonov** [comment]
Similar version merged and released.

**Comment by scamden** [comment]
oh haha i hadn't seen #5 either. but yes. i was going to do that exact same work lol

**Pull request closed without merging**
