### PR TITLE
link only modules with tsconfig file

### PR DESCRIPTION
**Pull request by Bessonov**

### CODE REVIEW

**Comment by scamden** [comment]
what needs to be tested with this one? could i help test it?

**Comment by Bessonov** [comment]
You said you have a some non-ts modules in monorepo. For me it's enough if you say that this change is working for you and don't break anything. I don't have any use case for that anymore.

**Comment by scamden** [comment]
i'll pull it down and try it :) one sec

**Comment by scamden** [comment]
just tried. it worked perfectly. even removed the previous erroneous reference.

**Comment by Bessonov** [comment]
Thank you very much for your contributions! v0.0.8 with this fix should be show up on npm soon.

**Comment by scamden** [comment]
thanks for this tool!

**Pull request merged**
